export enum AppEvents {
	ItemsChange = 'items:change',
	ModalOpen = 'modal:open',
	ModalClose = 'modal:close',
	PreviewChange = 'preview:change',
	CardSelect = 'card:select',
	CardBasket = 'card:basket',
	OrderReady = 'order:ready',
	OrderOpen = 'order:open',
	OrderSubmit = 'order:submit',
	OrderSuccess = 'order:success',
	AddressErrorsChange = 'addressErrors:change',
	ContactsErrorsChange = 'contactsErrors:change',
	ContactsSubmit = 'contacts:submit',
	BasketChange = 'basket:change',
	BasketOpen = 'basket:open',
	BasketAdd = 'basket:add',
	BasketRemove = 'basket:remove',
}
